### ISSUE TITLE
Does stopword remover already added?

### ISSUE THREAD

**Issue by santowijaya28** [RadhiFadlillah/go-sastrawi#3]
Try to looking for stop word remover since python version already added this feature

**Comment by RadhiFadlillah** [comment]
Sorry for late reply. Nope, I don't think I've added it.

I just checked `PySastrawi` and it seems newer than the PHP one. I'll port it to Go ASAP.

**Comment by RadhiFadlillah** [comment]
@santowijaya28 I've added example for using stopwords in readme.

Do note there is minor but breaking API change. For example, now `Tokenizer` doesn't exist anymore. Instead we can simply use `sastrawi.Tokenize`.
